In [115]:
import torch
import numpy as np

### Tensor Initialization

In [116]:
# from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# from ndarray
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# from another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")

# overriding dtype to pytorch float
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.1238, 0.6076],
        [0.6274, 0.5532]])


### Tensor Shapes

In [117]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}")
print(f"Ones Tensor:\n{ones_tensor}")
print(f"Zeros Tensor:\n{zeros_tensor}")

Random Tensor:
tensor([[0.4889, 0.9151, 0.8630],
        [0.9750, 0.5406, 0.8929]])
Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes
- Shape
- Datatype
- Device on which they are stored (CPU, GPU, etc)

In [118]:
tensor = torch.rand(3, 4)
print(f"Tensor:\n{tensor}\n")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Tensor:
tensor([[0.6951, 0.0345, 0.7434, 0.5925],
        [0.2676, 0.7217, 0.6948, 0.7912],
        [0.9387, 0.9355, 0.1791, 0.8370]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations
Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Edit > Notebook Settings.

### Switching to the GPU

In [119]:
if torch.cuda.is_available(): # I'm on apple silicon, no GPU :)
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

### NumPy Indexing/Slicing

In [120]:
tensor[:, 1] = 0 # 1st column is zero
print(f"Tensor:\n{tensor}")
print(f"Tensor shape: {tensor.shape}")

Tensor:
tensor([[0.6951, 0.0000, 0.7434, 0.5925],
        [0.2676, 0.0000, 0.6948, 0.7912],
        [0.9387, 0.0000, 0.1791, 0.8370]])
Tensor shape: torch.Size([3, 4])


### Joining tensors

In [121]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"Concatenated tensors:\n{t1}")
print(f"Concatenated tensor shape: {t1.shape}")

Concatenated tensors:
tensor([[0.6951, 0.0000, 0.7434, 0.5925, 0.6951, 0.0000, 0.7434, 0.5925, 0.6951,
         0.0000, 0.7434, 0.5925],
        [0.2676, 0.0000, 0.6948, 0.7912, 0.2676, 0.0000, 0.6948, 0.7912, 0.2676,
         0.0000, 0.6948, 0.7912],
        [0.9387, 0.0000, 0.1791, 0.8370, 0.9387, 0.0000, 0.1791, 0.8370, 0.9387,
         0.0000, 0.1791, 0.8370]])
Concatenated tensor shape: torch.Size([3, 12])


### Element-wise product

In [122]:
print(f"tensor.mul(tensor)\n{tensor.mul(tensor)}\n")
# alternative syntax
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor)
tensor([[0.4832, 0.0000, 0.5526, 0.3510],
        [0.0716, 0.0000, 0.4827, 0.6260],
        [0.8811, 0.0000, 0.0321, 0.7006]])

tensor * tensor 
 tensor([[0.4832, 0.0000, 0.5526, 0.3510],
        [0.0716, 0.0000, 0.4827, 0.6260],
        [0.8811, 0.0000, 0.0321, 0.7006]])


### Matrix Multiplication

In [123]:
print(f"tensor.matmul(tensor.T)\n{tensor.matmul(tensor.T)}\n")
# alternative syntax
print(f"tensor @ tensor.T\n{tensor @ tensor.T}")

tensor.matmul(tensor.T)
tensor([[1.3868, 1.1712, 1.2815],
        [1.1712, 1.1802, 1.0378],
        [1.2815, 1.0378, 1.6138]])

tensor @ tensor.T
tensor([[1.3868, 1.1712, 1.2815],
        [1.1712, 1.1802, 1.0378],
        [1.2815, 1.0378, 1.6138]])


### In-place operations
Operations that have a `_` suffix are in-place. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [124]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[0.6951, 0.0000, 0.7434, 0.5925],
        [0.2676, 0.0000, 0.6948, 0.7912],
        [0.9387, 0.0000, 0.1791, 0.8370]])

tensor([[5.6951, 5.0000, 5.7434, 5.5925],
        [5.2676, 5.0000, 5.6948, 5.7912],
        [5.9387, 5.0000, 5.1791, 5.8370]])


## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

### Tensor to NumPy

In [125]:
t = torch.ones(5)
print(f"Tensor: {t}\ndtype: {type(t)}")
n = t.numpy()
print(f"NumPy: {n}\ndtype: {type(n)}")

Tensor: tensor([1., 1., 1., 1., 1.])
dtype: <class 'torch.Tensor'>
NumPy: [1. 1. 1. 1. 1.]
dtype: <class 'numpy.ndarray'>


A change in the tensor reflects in the NumPy array.

In [126]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy to Tensor

In [127]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [128]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
